version: "3.9"
services:
  api:
    container_name: "flask_api"
    image: "python:3.11.2-bullseye"
    ports:
      - "5000:5000"
    volumes:
      - "./mre:/mre"
    working_dir: /mre
    command: >
      bash -c "apt-get update &&
      apt-get --no-install-recommends install libreoffice -y &&
      apt-get install -y libreoffice-java-common default-jre &&
      pip install -r requirements.txt &&
      python server.py"
